name: CI

on:
  push:
  pull_request:

jobs:
  minimum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build tools + python +debug/binutils
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make python3 python3-pip curl git gdb binutils

      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          syft version

      # Gitleaks kurulumla değil, action ile:
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup check
        run: |
          chmod +x scripts/setup.sh
          ./scripts/setup.sh

      - name: Build memory_regions
        run: make build-memory_regions

      - name: Generate logs
        run: make log-memory_regions

      - name: Inspect sections
        run: make inspect-memory-regions-sections > artifacts/logs/inspect_sections.log
      
      - name: Inspect segments
        run: make inspect-memory-regions-segments > artifacts/logs/inspect_segments.log
      # make secret-scan step'ini CI'dan kaldırdık çünkü action zaten tarıyor.

      - name: SBOM
        run: make sbom

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: memory-regions-artifacts
          path: artifacts/